### ISSUE TITLE
Claim ownership of the L2 contract

### ISSUE THREAD

**Issue by remiroyc** [TheArkProjekt/Starklane#40]
When a user bridges an NFT, a default token contract will be deployed on L2. Initially, the smart contract bridge will be the owner of this contract.

As the owner of an L1 collection, I must have the right to claim ownership of the token contract on L2.

**Comment by kwiss** [comment]
For that we need to exactly defined how to claim the contract on L2
it can be done with the L1 smart contract owner address, but if the ownership has been dropped it can be tricky, after several discussion it can be done with a trust third party that validate that the contract is own by a specified entity like a company or something else
