### ISSUE TITLE
Develop end-to-end tests for bridging an ERC721 token

### ISSUE THREAD

**Issue by remiroyc** [TheArkProjekt/Starklane#46]
Write an **end-to-end test** that:

- [ ] Deploys accounts
- [ ] Deploys the L1 and L2 bridge smart contracts
- [ ] Deploys an ERC721 token on L1
- [ ] Tests the deposit function of the bridge
- [ ] Verifies that a contract has been created on L2 and an NFT has been minted.

**Comment by kwiss** [comment]
we need to split theses into several issues, also i create a first one todo before https://github.com/ScreenshotLabs/starklane/issues/64
